(function(){
'use strict';
if(window.__KINO_REMOTE_110__)return;
window.__KINO_REMOTE_110__=1;
var S=['.b-content__inline_item','.b-topnav__item-link','.b-topnav__sub a','.b-search__field','.b-search__submit','.b-tophead__logo','.b-tophead__login','.b-tophead__register_page','.b-theme__switcher','.btn','.b-simple_season__item','.b-simple_episode__item','.b-translator__item','#cdnplayer-container','#oframecdnplayer','#pjsfrrscdnplayer','button','input:not([type=hidden])','select','textarea','[role=button]','[tabindex]:not([tabindex="-1"])','a[href]'].join(','),cur=null,list=[],timer=0,menu=null,pm=0,pc=[],pi=0,box=null,keys={},backAt=0;
function q(s,r){try{return(r||document).querySelector(s)}catch(e){return null}}
function qa(s,r){try{return(r||document).querySelectorAll(s)}catch(e){return[]}}
function r(e){try{return e.getBoundingClientRect()}catch(x){return null}}
function vis(e){var a,s;if(!e||e.nodeType!==1||e.disabled)return 0;try{s=getComputedStyle(e);if(s.display==='none'||s.visibility==='hidden'||+s.opacity<.04)return 0}catch(x){}a=r(e);return!!(a&&a.width>6&&a.height>6)}
function docr(e){var a=r(e);return a?{left:a.left+pageXOffset,right:a.right+pageXOffset,top:a.top+pageYOffset,bottom:a.bottom+pageYOffset,width:a.width,height:a.height}:null}
function stop(e){try{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}catch(x){}}
function mouse(e,t,x,y){var v;if(!e)return;var a=r(e);x=x==null&&a?a.left+a.width/2:x;y=y==null&&a?a.top+a.height/2:y;try{v=new MouseEvent(t,{bubbles:true,cancelable:true,view:window,clientX:x,clientY:y,button:0})}catch(z){try{v=document.createEvent('MouseEvents');v.initMouseEvent(t,true,true,window,1,x,y,x,y,false,false,false,false,0,null)}catch(k){v=null}}try{if(v)e.dispatchEvent(v)}catch(k){}}
function toast(t){var n=q('#kino-toast');if(!n){n=document.createElement('div');n.id='kino-toast';(document.body||document.documentElement).appendChild(n)}n.textContent=t;n.className='show';clearTimeout(n._t);n._t=setTimeout(function(){n.className=''},1400)}
function style(){if(q('#kino-style'))return;var s=document.createElement('style');s.id='kino-style';s.textContent="*:focus{outline:none!important}[data-rf='1']{outline:2px solid #00eaff!important;outline-offset:2px!important;box-shadow:0 0 0 1px #6b5cff,0 0 0 3px rgba(255,43,214,.88),0 0 10px rgba(0,234,255,.45),0 0 14px rgba(255,43,214,.25)!important;position:relative!important;z-index:2147483000!important}.b-content__inline_item[data-rf='1']{transform:scale(1.02)!important}html.rf-full [data-rf='1']{outline:none!important;box-shadow:none!important;transform:none!important}[data-pf='1']{outline:2px solid #00eaff!important;outline-offset:1px!important;box-shadow:0 0 0 1px #6b5cff,0 0 0 3px rgba(255,43,214,.82),0 0 9px rgba(0,234,255,.42)!important}#kino-pbox{position:fixed;display:none;pointer-events:none;border:2px solid #00eaff;box-shadow:0 0 0 1px #6b5cff,0 0 0 3px rgba(255,43,214,.82),0 0 10px rgba(0,234,255,.42);border-radius:4px;z-index:2147483646}#kino-toast{position:fixed;right:25px;bottom:25px;padding:12px 18px;background:#080b0eee;border:1px solid #00eaff;box-shadow:0 0 0 1px #6b5cff,0 0 10px rgba(255,43,214,.5);color:#fff;font:700 18px Arial;z-index:2147483647;opacity:0;pointer-events:none}#kino-toast.show{opacity:1}";(document.head||document.documentElement).appendChild(s)}
function full(){return document.fullscreenElement||document.webkitFullscreenElement||null}
function zoom(){var w=screen&&screen.width||innerWidth,z=full()?1:w>=1600?1.55:w>=1100?1.28:1.12;try{document.documentElement.style.zoom=z;document.documentElement.classList[full()?'add':'remove']('rf-full')}catch(e){}}
function target(e){if(!e||!e.closest)return e;return e.closest('.b-content__inline_item')||e}
function refresh(){var n=qa(S),u={},a=[],i,e,d,k;timer=0;for(i=0;i<n.length;i++){e=target(n[i]);if(!vis(e))continue;d=docr(e);if(!d)continue;k=Math.round((d.left+d.right)/6)+':'+Math.round((d.top+d.bottom)/6);if(u[k]){if(d.width*d.height<u[k].d.width*u[k].d.height){u[k].e=e;u[k].d=d}}else{u[k]={e:e,d:d};a.push(u[k])}}list=a;if(cur&&!document.documentElement.contains(cur))cur=null;if(!cur)start()}
function later(ms){clearTimeout(timer);timer=setTimeout(refresh,ms||300)}
function item(e){return e&&e.closest?e.closest('.b-topnav__item'):null}
function sub(e){var i=item(e);return i&&q('.b-topnav__sub',i)}
function closeMenu(){var s;if(!menu)return;s=q('.b-topnav__sub',menu);try{menu.classList.remove('open');menu.classList.remove('active');if(s&&s.getAttribute('data-rx')){s.style.cssText='';s.removeAttribute('data-rx')}}catch(e){}menu=null}
function openMenu(e,first){var i=item(e),s=sub(e),a;if(!i||!s)return 0;if(menu&&menu!==i)closeMenu();menu=i;mouse(i,'mouseover');mouse(e,'mouseover');try{i.classList.add('open');i.classList.add('active');s.style.setProperty('display','block','important');s.style.setProperty('visibility','visible','important');s.style.setProperty('opacity','1','important');s.style.setProperty('pointer-events','auto','important');s.setAttribute('data-rx','1')}catch(x){}later(60);if(first)setTimeout(function(){a=q('a[href],button,[role=button]',s);if(vis(a))focus(a,1)},80);return 1}
function focus(e,scroll){if(!vis(e))return 0;try{if(cur&&cur!==e)cur.removeAttribute('data-rf')}catch(x){}cur=e;try{e.setAttribute('data-rf','1');e.focus({preventScroll:true})}catch(x){try{e.focus()}catch(k){}}if(e.closest&&e.closest('.b-topnav__sub'))openMenu(e,0);else if(e.classList&&e.classList.contains('b-topnav__item-link'))mouse(e,'mouseover');else if(menu&&item(e)!==menu)closeMenu();if(scroll!==0)try{e.scrollIntoView({block:'center',inline:'center',behavior:'auto'})}catch(x){}return 1}
function start(){var p,c,m,i;if(/\/[^\/]+\.html/i.test(location.href)){p=player();if(vis(p)){focus(p,1);return}}c=qa('.b-content__inline_item');for(i=0;i<c.length;i++)if(vis(c[i])){focus(c[i],1);return}m=q('.b-topnav__item-link,.b-search__field,a[href],button');if(vis(m))focus(m,0)}
function score(a,b,dir){var ax=(a.left+a.right)/2,ay=(a.top+a.bottom)/2,bx=(b.left+b.right)/2,by=(b.top+b.bottom)/2,dx=bx-ax,dy=by-ay,p,s,o,g;if(dir==='left'){if(dx>=-2)return 1/0;p=-dx;s=Math.abs(dy);o=Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));g=Math.max(0,a.left-b.right)}else if(dir==='right'){if(dx<=2)return 1/0;p=dx;s=Math.abs(dy);o=Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));g=Math.max(0,b.left-a.right)}else if(dir==='up'){if(dy>=-2)return 1/0;p=-dy;s=Math.abs(dx);o=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left));g=Math.max(0,a.top-b.bottom)}else{if(dy<=2)return 1/0;p=dy;s=Math.abs(dx);o=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left));g=Math.max(0,b.top-a.bottom)}return g*4+p+s*(o?.55:2.1)-(o?850:0)}
function move(dir){var a=docr(cur),b=null,v=1/0,i,z;if(dir==='down'&&cur&&cur.classList&&cur.classList.contains('b-topnav__item-link')&&openMenu(cur,1))return;if(!a){start();return}for(i=0;i<list.length;i++){if(list[i].e===cur)continue;z=score(a,list[i].d,dir);if(z<v){v=z;b=list[i].e}}if(b)focus(b,1);else scrollTo(pageXOffset,pageYOffset+(dir==='down'?innerHeight*.65:dir==='up'?-innerHeight*.65:0))}
function player(){return q('#oframecdnplayer')||q('#cdnplayer-container')||q('#pjsfrrscdnplayer')}
function video(){return q('#oframecdnplayer video,#cdnplayer-container video,#pjsfrrscdnplayer video,video')}
function wake(){var p=player(),a=r(p);if(a){mouse(p,'mousemove',a.left+a.width*.5,a.bottom-32);mouse(p,'mouseover',a.left+a.width*.5,a.bottom-32)}}
function pRect(c){var p,a;if(!c)return null;if(!c.v)return r(c.e);p=player();a=r(p);return a?{left:a.left+a.width*c.x-c.w/2,right:a.left+a.width*c.x+c.w/2,top:a.top+a.height*c.y-c.h/2,bottom:a.top+a.height*c.y+c.h/2,width:c.w,height:c.h}:null}
function pCollect(){var p=player(),pr=r(p),n,a=[],u={},i,e,d,k,t,ar;if(!p||!pr){pc=[];return}n=qa('button,[role=button],[onclick],a[href],pjsdiv,[style*="cursor: pointer"],[style*="pointer-events: auto"]',p);for(i=0;i<n.length;i++){e=n[i];if(!vis(e))continue;d=r(e);if(!d||d.left<pr.left||d.right>pr.right||d.top<pr.top||d.bottom>pr.bottom)continue;ar=d.width*d.height;if(ar>pr.width*pr.height*.34)continue;t=(e.textContent||'').replace(/\s+/g,' ').trim();k=Math.round((d.left+d.right)/8)+':'+Math.round((d.top+d.bottom)/8);if(!u[k]){u[k]={e:e,t:t,a:ar};a.push(u[k])}else if(ar<u[k].a){u[k].e=e;u[k].t=t;u[k].a=ar}}a.push({v:1,act:'play',x:.065,y:.91,w:58,h:48});a.push({v:1,act:'settings',x:.915,y:.91,w:48,h:46});a.push({v:1,act:'full',x:.968,y:.91,w:48,h:46});pc=a}
function pClear(){var i;for(i=0;i<pc.length;i++)if(pc[i].e)try{pc[i].e.removeAttribute('data-pf')}catch(x){}if(box)box.style.display='none'}
function pFocus(i){var c,d;pClear();if(!pc.length)return;pi=Math.max(0,Math.min(i,pc.length-1));c=pc[pi];d=pRect(c);if(!d)return;if(c.e)try{c.e.setAttribute('data-pf','1')}catch(x){}if(!box){box=document.createElement('div');box.id='kino-pbox';(document.body||document.documentElement).appendChild(box)}box.style.left=d.left-2+'px';box.style.top=d.top-2+'px';box.style.width=d.width+4+'px';box.style.height=d.height+4+'px';box.style.display='block'}
function pEnter(){if(!player())return 0;pm=1;wake();pCollect();pFocus(Math.max(0,pc.length-3));toast('PLAYER MODE: bultiņas • OK • RETURN');return 1}
function pExit(t){pm=0;pClear();pc=[];pi=0;if(t)toast('PLAYER MODE aizvērts')}
function pMove(dir){var a=pRect(pc[pi]),b=-1,v=1/0,i,d,z;wake();if(!a)return;for(i=0;i<pc.length;i++){if(i===pi)continue;d=pRect(pc[i]);if(!d)continue;z=score(a,d,dir);if(z<v){v=z;b=i}}if(b>=0)pFocus(b)}
function play(){var v=video();if(!v)return 0;try{v.paused?v.play():v.pause();return 1}catch(e){return 0}}
function seek(n){var v=video();if(!v)return;try{v.currentTime=Math.max(0,Math.min(isFinite(v.duration)?v.duration:v.currentTime+n,v.currentTime+n))}catch(e){}}
function fs(){var p=player()||video(),v=video();pExit(0);try{if(p.requestFullscreen)p.requestFullscreen();else if(p.webkitRequestFullscreen)p.webkitRequestFullscreen();else if(v&&v.webkitEnterFullscreen)v.webkitEnterFullscreen()}catch(e){}}
function clickPoint(x,y){var e;try{e=document.elementFromPoint(x,y)}catch(k){}if(e){mouse(e,'mousedown',x,y);mouse(e,'mouseup',x,y);mouse(e,'click',x,y)}}
function pOk(){var c=pc[pi],d;if(!c)return;if(c.v){if(c.act==='play'){play();return}if(c.act==='full'){fs();return}d=pRect(c);if(d)clickPoint((d.left+d.right)/2,(d.top+d.bottom)/2)}else try{c.e.click()}catch(x){mouse(c.e,'click')}setTimeout(function(){pCollect();pFocus(Math.min(pi,pc.length-1))},180)}
function activate(e){var a,tag=(e&&e.tagName||'').toLowerCase();if(!e)return;if(e.classList&&e.classList.contains('b-topnav__item-link')&&openMenu(e,1))return;if(e.classList&&e.classList.contains('b-content__inline_item')){a=q('a[href]',e);if(a){a.click();return}}if(e===player()||tag==='video'){pEnter();return}try{e.click()}catch(x){mouse(e,'click')}}
function exitFull(){try{if(document.exitFullscreen)document.exitFullscreen();else if(document.webkitExitFullscreen)document.webkitExitFullscreen()}catch(e){}}
function back(e){stop(e);if(pm){pExit(1);return}if(menu){closeMenu();return}if(full()){exitFull();return}if(history.length>1){history.back();return}if(Date.now()-backAt<1500){try{tizen.application.getCurrentApplication().exit()}catch(x){window.close()}}else{backAt=Date.now();toast('Nospied RETURN vēlreiz, lai aizvērtu')}}
function reg(){var n=['MediaPlay','MediaPause','MediaPlayPause','MediaFastForward','MediaRewind'],i,k;try{for(i=0;i<n.length;i++){tizen.tvinputdevice.registerKey(n[i]);k=tizen.tvinputdevice.getKey(n[i]);if(k)keys[k.code]=n[i]}}catch(e){}}
function key(e){var c=e.keyCode||e.which,n=keys[c],a=document.activeElement;if(c===10009||c===10182){back(e);return}if(n==='MediaPlay'||n==='MediaPause'||n==='MediaPlayPause'){stop(e);play();return}if(n==='MediaFastForward'){stop(e);seek(10);return}if(n==='MediaRewind'){stop(e);seek(-10);return}if(pm){if(c===37||c===38||c===39||c===40){stop(e);pMove(c===37?'left':c===38?'up':c===39?'right':'down');return}if(c===13||c===65376){stop(e);pOk();return}}if(a===cur&&(a.tagName==='INPUT'||a.tagName==='TEXTAREA'))return;if(c===37||c===38||c===39||c===40){stop(e);move(c===37?'left':c===38?'up':c===39?'right':'down');return}if(c===13||c===65376){stop(e);cur?activate(cur):start()}}
function init(){var o;if(!document.documentElement)return;style();zoom();reg();document.addEventListener('keydown',key,true);document.addEventListener('click',function(){later(220)},true);document.addEventListener('fullscreenchange',function(){zoom();later(160)},false);document.addEventListener('webkitfullscreenchange',function(){zoom();later(160)},false);addEventListener('resize',function(){zoom();later(220);if(pm){pCollect();pFocus(pi)}},false);if(window.MutationObserver){o=new MutationObserver(function(){later(300);if(pm)setTimeout(function(){pCollect();pFocus(Math.min(pi,pc.length-1))},110)});o.observe(document.documentElement,{childList:true,subtree:true})}setTimeout(function(){refresh();start()},600);setTimeout(refresh,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());